# 1. Mit dem Terminal in das Verzeichnis IFCViewer navigieren.
# 2. docker build --tag ifc:latest .
# 3. docker run -d -p 80:80 --name ifc ifc:latest

FROM nginx:latest

COPY . /usr/share/nginx/html